CREATE TABLE "authorization"
(
    id                            VARCHAR(255) NOT NULL,
    registered_client_id          VARCHAR(255),
    principal_name                VARCHAR(255),
    authorization_grant_type      VARCHAR(255),
    authorized_scopes             BLOB,
    attributes                    BLOB,
    state                         VARCHAR(500),
    authorization_code_value      BLOB,
    authorization_code_issued_at  TIMESTAMP,
    authorization_code_expires_at TIMESTAMP,
    authorization_code_metadata   VARCHAR(255),
    access_token_value            BLOB,
    access_token_issued_at        TIMESTAMP,
    access_token_expires_at       TIMESTAMP,
    access_token_metadata         BLOB,
    access_token_type             VARCHAR(255),
    access_token_scopes           BLOB,
    refresh_token_value           BLOB,
    refresh_token_issued_at       TIMESTAMP,
    refresh_token_expires_at      TIMESTAMP,
    refresh_token_metadata        BLOB,
    oidc_id_token_value           BLOB,
    oidc_id_token_issued_at       TIMESTAMP,
    oidc_id_token_expires_at      TIMESTAMP,
    oidc_id_token_metadata        BLOB,
    oidc_id_token_claims          BLOB,
    user_code_value               BLOB,
    user_code_issued_at           TIMESTAMP,
    user_code_expires_at          TIMESTAMP,
    user_code_metadata            BLOB,
    device_code_value             BLOB,
    device_code_issued_at         TIMESTAMP,
    device_code_expires_at        TIMESTAMP,
    device_code_metadata          BLOB,
    CONSTRAINT pk_authorization PRIMARY KEY (id)
);

CREATE TABLE "authorization_consent"
(
    registered_client_id VARCHAR(255) NOT NULL,
    principal_name       VARCHAR(255) NOT NULL,
    authorities          VARCHAR(1000),
    CONSTRAINT pk_authorization_consent PRIMARY KEY (registered_client_id, principal_name)
);

CREATE TABLE "client"
(
    id                            VARCHAR(255) NOT NULL,
    client_id                     VARCHAR(255),
    client_id_issued_at           TIMESTAMP,
    client_secret                 VARCHAR(255),
    client_secret_expires_at      TIMESTAMP,
    client_name                   VARCHAR(255),
    client_authentication_methods VARCHAR(1000),
    authorization_grant_types     VARCHAR(1000),
    redirect_uris                 VARCHAR(1000),
    post_logout_redirect_uris     VARCHAR(1000),
    scopes                        VARCHAR(1000),
    client_settings               VARCHAR(2000),
    token_settings                VARCHAR(2000),
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE "role_data"
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted BOOLEAN NOT NULL,
    name    VARCHAR(255),
    CONSTRAINT pk_role_data PRIMARY KEY (id)
);

CREATE TABLE "token_data"
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted     BOOLEAN NOT NULL,
    token_value VARCHAR(255),
    user_id     BIGINT,
    expiry_date TIMESTAMP,
    CONSTRAINT pk_token_data PRIMARY KEY (id)
);

CREATE TABLE "user_data"
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deleted           BOOLEAN NOT NULL,
    name              VARCHAR(255),
    email             VARCHAR(255),
    hashed_password   VARCHAR(255),
    is_email_verified BOOLEAN NOT NULL,
    CONSTRAINT pk_user_data PRIMARY KEY (id)
);

CREATE TABLE "user_role_data"
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

ALTER TABLE "token_data"
    ADD CONSTRAINT FK_TOKEN_DATA_ON_USER FOREIGN KEY (user_id) REFERENCES "user_data" (id);

ALTER TABLE "user_role_data"
    ADD CONSTRAINT fk_useroldat_on_roles FOREIGN KEY (role_id) REFERENCES "role_data" (id);

ALTER TABLE "user_role_data"
    ADD CONSTRAINT fk_useroldat_on_users FOREIGN KEY (user_id) REFERENCES "user_data" (id);