ALTER TABLE role_data
    ALTER COLUMN IS_DELETED RENAME TO deleted;

ALTER TABLE token_data
    ALTER COLUMN IS_DELETED RENAME TO deleted;

ALTER TABLE user_data
    ALTER COLUMN IS_DELETED RENAME TO deleted;